name: Geek Style

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: docker pull and build 
      run: bash docker/start_geek.sh
    - name: docker exec test_segmentation
      run: docker exec -u apollo geek_pcl_apollo bash -c "python3 tests/test_segmentation.py"
    - name: docker exec filter
      run: docker exec -u apollo geek_pcl_apollo bash -c "python3 tests/test_filter.py"
