name: Geek Style

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: docker pull and build 
      run: bash docker/start_geek.sh
    - name: docker exec 
      run: docker exec -u $USER geek_pcl_$USER bash -c "grep -l test tests/*.py | xargs -n 1 python3"
